name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            platform: linux-x64
            crypto: auto
            configure_extra: ""
          - crypto: nettle
            runner: ubuntu-22.04
            platform: linux-x64-nettle
            configure_extra: ""
          - runner: ubuntu-22.04-arm
            platform: linux-arm64
            crypto: auto
            configure_extra: ""
          - runner: macos-14
            platform: macos-arm64
            crypto: auto
            configure_extra: "--with-utempter=no"

    steps:
    - uses: actions/checkout@v4

    - name: "setup linux build environment"
      if: ${{ startsWith(matrix.runner, 'ubuntu') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev libutempter-dev autoconf automake nettle-dev

    - name: "setup macos build environment"
      if: ${{ startsWith(matrix.runner, 'macos') }}
      run: brew install protobuf automake autoconf pkg-config

    - name: "generate build scripts"
      run: ./autogen.sh

    - name: ${{ format('configure (crypto {0})', matrix.crypto) }}
      run: ./configure --enable-examples ${{ (matrix.crypto != 'auto' && format('--with-crypto-library={0}', matrix.crypto)) || '' }} ${{ matrix.configure_extra }}

    - name: "build"
      run: make V=1

    - name: "smoke test"
      run: |
        src/frontend/mosh-client --version
        src/frontend/mosh-server --version
